In [412]:
import numpy as np
import pandas as pd

In [413]:
df = pd.read_csv("C:\\Work\\AI_Devoloping\\ML\\Project\\Guess_Price_Home\\Data.csv")
df.head()

   Floor_Area  Neiborhood  Room  Year_Built         Price
0          92           1     3        1405  2.550000e+10
1         107           1     2        1399  3.500000e+10
2         255           1     4        1405  1.300000e+11
3         170           1     3        1405  5.150000e+10
4          68           1     1        1394  9.900000e+09

In [414]:
x = df.drop(["Price"], axis=1)
y = df["Price"]

In [415]:
x = np.array(x)
y = np.array(y)

In [416]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaler.fit_transform(x)

array([[-0.58604412, -1.46358345,  0.60878078,  1.08134043],
       [-0.41581442, -1.46358345, -0.56195149,  0.21395506],
       [ 1.26378531, -1.46358345,  1.77951304,  1.08134043],
       [ 0.29915033, -1.46358345,  0.60878078,  1.08134043],
       [-0.85841165, -1.46358345, -1.73268375, -0.50886609],
       [ 1.09355561, -1.46358345,  1.77951304,  0.50308352],
       [-0.20019013, -0.15681251, -0.56195149,  1.08134043],
       [ 0.52612327, -0.15681251,  0.60878078, -1.23168723],
       [ 0.70770162, -0.15681251,  0.60878078,  0.9367762 ],
       [-0.55199818, -0.15681251, -0.56195149, -0.0751734 ],
       [-0.81301706, -0.15681251, -0.56195149, -0.36430186],
       [ 1.26378531,  1.14995842,  0.60878078,  0.21395506],
       [ 0.18566386,  1.14995842,  0.60878078,  0.21395506],
       [ 0.68500432,  1.14995842,  0.60878078,  0.9367762 ],
       [-1.06268729,  1.14995842, -1.73268375, -0.0751734 ],
       [-0.92650353,  1.14995842, -0.56195149, -0.65343031],
       [-0.38176848,  1.14995842, -0.56195149, -1.52081569],
       [-0.66548465,  1.14995842, -0.56195149,  0.06939083],
       [-1.06268729,  1.14995842, -1.73268375, -1.80994415],
       [-0.85841165,  1.14995842, -0.56195149, -2.53276529],
       [-0.26828201, -0.15681251, -0.56195149, -0.50886609],
       [-0.55199818, -0.15681251, -0.56195149, -0.94255877],
       [-0.02996043, -0.15681251,  0.60878078,  0.79221197],
       [ 3.47677144, -0.15681251,  1.77951304,  1.08134043],
       [-0.26828201, -0.15681251,  0.60878078,  0.9367762 ]])

In [417]:
result_df = pd.read_csv("C:\\Work\\AI_Devoloping\\ML\\Project\\Guess_Price_Home\\Test.csv")        
result_df

   Floor_Area  Neiborhood  Room  Year_Built
0         200           2     1        1400

In [ ]:
from sklearn.linear_model import LinearRegression
model_LR =  LinearRegression()
model_LR.fit(x, y)

LinearRegression()

In [419]:
result_LR = model_LR.predict(result_df)
result_LR = result_LR[0]
print(f"your home price is T.{result_LR}")

your home price is T.37254421558.83276

c:\Users\mahan.ly\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2684: UserWarning: X has feature names, but LinearRegression was fitted without feature names
  warnings.warn(